### ISSUE TITLE
Compile on Windows and other rendering algorithms.

### ISSUE THREAD

**Issue by goofoo** [IteratorAdvance/taichi#9]
Please add info to "Getting Started" how compile on windows. 
Thanks.

**Comment by IteratorAdvance** [comment]
Sure.  I think it's pretty simple with VS2015 and CMake. Also make sure to set TAICHI_ROOT.

**Comment by goofoo** [comment]
Thanks.
How about implement some algorithms:
- [Unbiased photon gathering for light transport simulation](http://haoqin87.com/upg.html) 
- [Manifold next event estimation](https://jo.dreggn.org/home/2015_mnee_talk.pdf)
- [Improved half vector space light transport ](https://jo.dreggn.org/home/2015_ihslt_talk.pdf)
- [Unifying points, beams, and paths in volumetric light transport simulation](http://www.smallupbp.com/)

**Comment by IteratorAdvance** [comment]
Hi Goofoo,

These are all amazing algorithms and it's definitely good to have them in Taichi. 

I guess (improved) HSLT needs path space MLT as a base and UPBP requires a lot more work (like photon beams). Not sure about manifold next event estimation and unbiased photon gathering, but I'll take a look at them later. Now we already have primary sample space MLT and path space MLT haven't been integrated. In my personal impression path space MLT requires more amount of work to implement.

Though now we already have fancy stuff like (AMCMC)VCM/UPS, I haven't spent much time verifying these implementations. Also, now volumetric effects are limited to unidirectional PT, and maybe it's better to first make VCM volumetric before implementing UPBP.

Since I recently only have limited time for Taichi, and I don't know why Taichi just get popular yesterday and people are asking for tutorials, documentation, and stable interface. Thus I plan to first do software engineering so that interested people can make use of it.

If you would like to, you are truly welcome to add whatever you want to Taichi, and possibly I'll join you in implementing these fancy stuff soon, after I finished these software engineering tasks.

Thanks.

**Comment by IteratorAdvance** [comment]
You are right that "Robust Light Transport Simulation via Metropolized Bidirectional Estimators" was implemented in mcmcups.cpp. Actually I think I mentioned this implementation as "Markov Chain Monte Carlo UPS/VCM" in the 12th item. MCMCUPS is a (too) new rendering GI algorithm and I implemented my understanding of the paper within 3 days (what a big rush...) and without the "supplementary document", where some details were included. It's like the authors haven't posted the supplementary document so far, so what I have implemented was merely my understanding based on the paper...
